### ISSUE TITLE
用最新版操作和飞信不能获取到特定id，旧版可以

### ISSUE THREAD

**Issue by javadevelopuser** [hyb1996/AutoJs-Docs#15]
运行环境：
4.1.1a Alpha2-armeabi-v7a-release.apk
com.chinasofti.rcs_6.2.6.1205_2018061571.apk
https://sj.qq.com/myapp/detail.htm?apkName=com.chinasofti.rcs
不能获取到获取到和飞信app打开后右上角“+”弹出菜单。旧版本（Auto.js_4.1.0 Alpha5.apk）可以。
代码如下：
log("点击“+”按钮");
    id("action_add").findOne().click();
    log("点击“免费短信”按钮");

**Comment by nmdx** [comment]
发现webkit等类似网页嵌套下  内部无法用id获取数据   话说这软件是不是鸽了。。
