### ISSUE TITLE
每次获取屏幕权限都会出现系统提示框

### ISSUE THREAD

**Issue by ADMarcelo** [hyb1996/AutoJs-Docs#29]
每次调用requestScreenCapture()，系统都会出现“在投射/录制时显示敏感信息”提示框。需要人为手动点击一下“立即开始”,脚本才会继续执行。这样就没法完全实现定时自动化了。网上找了好久也没想到解决办法。手机是Pixel2 android 10（已启用无障碍模式，未root）

**Comment by pboymt** [comment]
不是可以选择下次不再提示吗？

**Comment by ColorfulGhost** [comment]
![IMG_6361](https://user-images.githubusercontent.com/11071219/173033124-134766de-e4db-40d6-a39c-77d00af54809.JPG)
请问如何关闭该提示，我没有找到这个不再提示的选择。

**Comment by ADMarcelo** [comment]
当时使用多线程，让另一个线程做模拟点击“立即开始”按钮的吧，好像是。https://pro.autojs.org/docs/#/zh-cn/threads

**Comment by ColorfulGhost** [comment]
> 当时使用多线程，让另一个线程做模拟点击“立即开始”按钮的吧，好像是。https://pro.autojs.org/docs/#/zh-cn/threads

恩恩 ，已经实现啦 多谢~
```
function screenShot() {
  device.wakeUp()
  threads.start(function () {
    sleep(1000)
    var beginBtn;
    if (beginBtn = classNameContains("Button").textContains("立即开始").findOne(2000)) {
      beginBtn.click();
    }
  });
  if (!requestScreenCapture(false)) {
    toast("截图请求失败！")
  }
  sleep(1000);
  let path = "/storage/emulated/0/screenShot/wework-" + getCurrentDate() + getCurrentTime() + ".png";
  captureScreen(path);
  sleep(1000);
  sendScreenShot(path)
  toast("截图完成！")
}
```

**Comment by ADMarcelo** [comment]
线程外面再加一个定时任务，应该可行。笨办法
