### ISSUE TITLE
这个软件已经不更新了，是否有替代品?

### ISSUE THREAD

**Issue by yimudi003** [hyb1996/AutoJs-Docs#34]
广告已屏蔽

**Comment by pboymt** [comment]
打广告的死个妈哦



---原始邮件---
发件人: "yimudi003"<notifications@github.com&gt;
发送时间: 2020年6月15日(周一) 上午9:26
收件人: "hyb1996/AutoJs-Docs"<AutoJs-Docs@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [hyb1996/AutoJs-Docs] 这个软件已经不更新了，是否有替代品? (#34)




 
听说Auto.js 已经不更新了，朋友跟推荐了EasyClick这个软件，听说还可以，大家有没有用过？
 https://easyclick.gitee.io/docs/index.html
