### ISSUE TITLE
大佬，多个.js文件怎么打包成apk呀

### ISSUE THREAD

**Issue by 627992512** [hyb1996/AutoJs-Docs#43]
如题，除了合并成一个文件以外还有别的办法吗

**Comment by pboymt** [comment]
不是可以用project.json标记为项目么？



---原始邮件---
发件人: "627992512"<notifications@github.com&gt;
发送时间: 2020年10月21日(周三) 下午4:37
收件人: "hyb1996/AutoJs-Docs"<AutoJs-Docs@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [hyb1996/AutoJs-Docs] 大佬，多个.js文件怎么打包成apk呀 (#43)




 
如题，除了合并成一个文件以外还有别的办法吗

**Comment by 627992512** [comment]
哇，解决了，感谢大佬
