### ISSUE TITLE
抖音元素无法点击

### ISSUE THREAD

**Issue by 334660335** [hyb1996/AutoJs-Docs#47]
两个问题：
1、https://pro.autojs.org/，请问这个是你们的官网吗？我花了45淘宝购买的

2、现在发现

      环境：OPPO、华为 真机；
      版本：autojs pro 8.2.1、autojs 4.1.0Apltha 5
      代码:   id("b0b").className("android.widget.ImageView").findOne().parent().click()

      在付费版autojs pro无法点击， 在auto js老版本下可以，这。。。很尴尬啊！？？是抖音被做了限制吗？
      难道我应该用免费的吗？

**Comment by linyugeng1225** [comment]
我是Auto.js pro和Auto.js普通版的老用户，你提到的第一点，这确实就是Auto.js pro的官网，pro版本收费，均为属实；Auto.js相比普通版功能增多，加上普通版免费，许多图谋不轨的使用者利用普通版开发许多类似刷屏等恶意软件，甚至盗版普通版篡改成付费版，众多流氓使用者造就今日Auto.js pro收费，且主动屏蔽了自动操作模块在抖音，qq，微信等软件上的功能。也就是说，自动操作在许多软件中无法生效。如果需要使用，需要使用普通版。

**Comment by 334660335** [comment]
> 屏蔽了自动操作模块在抖音，qq，微信等软件上的功能。也就是说，自动操作在许多软件中无法生效。如果需要使用，需要使用普通版
看来只能用普通版本了 好难受啊

**Comment by hyb1996** [comment]
无奈之举
