### ISSUE TITLE
微信8.0.1无法识别

### ISSUE THREAD

**Issue by lileieiei** [hyb1996/AutoJs-Docs#59]
不知道咋解决，有跟我一样的嘛？

**Comment by pboymt** [comment]
8.0开始就屏蔽了啊



---原始邮件---
发件人: "lileieiei"<notifications@github.com&gt;
发送时间: 2021年2月24日(周三) 上午9:31
收件人: "hyb1996/AutoJs-Docs"<AutoJs-Docs@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [hyb1996/AutoJs-Docs] 微信8.0.1无法识别 (#59)




 
不知道咋解决，有跟我一样的嘛？

**Comment by shiny** [comment]
7.0.22 也不行，不知道哪个版本可以，需要一个个试下
