### ISSUE TITLE
autojs做不到锁屏么

### ISSUE THREAD

**Issue by CodingDogzxg** [hyb1996/AutoJs-Docs#87]
有运行完脚本锁屏的需求 autojs的权限做不到锁定屏幕么？

**Comment by HOLLYwyh** [comment]
我也有这样的问题 官方文档里貌似没有锁屏的接口

**Comment by CodingDogzxg** [comment]
> 我也有这样的问题 官方文档里貌似没有锁屏的接口

是有这个接口的 在console demo里 但是无root无效 可以使用安全中心带的一键锁屏加屏幕点击事件模拟
